[package]
name = "opengl-hello_world"
version = "0.1.0"
authors = ["Jonathas-Conceicao <jadoliveira@inf.ufpel.edu.br>"]
edition = "2018"

[dependencies]
cgmath = "0.16"
gl = "0.10"
glfw = "0.23"
image = "0.19"
tobj = "0.1"
num = "0.2"
rand = "0.5"